baseURL = "https://www.rdegges.com"
languageCode = "en-us"
enableRobotsTXT = true
metaDataFormat = "yaml"
newContentEditor = "nvim"
title = "Randall Degges"

[permalinks]
post = "/:year/:title"

[params]
author = "Randall Degges"
description = "The personal website of Randall Degges: programmer, speaker, author and entrepreneur."
email = "r@rdegges.com"
subtitle = "Random Thoughts of a Happy Programmer"
emailSubscriptionFormAction = "https://buttondown.email/api/emails/embed-subscribe/rdegges"

[[params.navLinks]]
title = "Bluesky"
url = "https://bsky.app/profile/rdegges.com"

[[params.navLinks]]
title = "GitHub"
url = "https://github.com/rdegges"

[[params.navLinks]]
title = "Talks"
url = "https://speakerdeck.com/rdegges"

[[params.navLinks]]
title = "Email"
url = "mailto:r@rdegges.com"

[author]
name = "Randall Degges"
email = "r@rdegges.com"

[outputFormats.RSS]
baseName = "feed"

[[deployment.targets]]
URL = "s3://rdegges-www?endpoint=gateway.storjshare.io&disableSSL=false&s3ForcePathStyle=true"
name = "Storj"

[[deployment.targets]]
cloudFrontDistributionID = "E3VRTXFJ9OEPFY"
URL = "s3://www.rdegges.com"
name = "AWS"

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = false
noHl = false
style = 'autumn'
tabWidth = 4
